#!/usr/bin/env python


def configure(ctx):
	print("Nothing to configure in 'test'.")
	

def build(ctx):
	print("Nothing to build in 'test'.")
	

def info(ctx):
	pass


def test(ctx):
	print("Nothing to test in 'test'.")

